### ISSUE TITLE
Array issue on tessolate

### ISSUE THREAD

**Issue by ActiveMargins** [GPlates/gplately#159] opened 2024-01-25 23:11 UTC
I'm getting back to work on a gplates project. I'm getting an array error when tessolating data. 
![ArrayError](https://github.com/GPlates/gplately/assets/52948432/8bdf91f4-71a5-42d7-acd7-9aa131ebfde2)
I could not figure out where it was coming from in my code, so went to the introductory notebooks (pictured above). The code above is copied from "gplately/notebooks/01-GettingStarted"

If the problem is due to a recent update -
I went through to check my versions. Everything is up-to-date except for my gplates-model-manager. In Anaconda Navigator it says model-manager is up to date (1.2.0), while in Anaconda Prompt it says the model-manager is 1.1.0. When I try to update via pip in prompt it says it is everything is up to date. I am having issues updating it through. Any help on any of this would be awesome.

**Comment by michaelchin** [comment] 2024-01-26 05:59
May I ask which plate model you were using? Muller2019? It seems to me that this problem might caused by lacking topology files in the plate model.

**Comment by ActiveMargins** [comment] 2024-01-26 15:39
Yes I was using Muller2019. Has anything changed with that model on the data server? I was using it for a lot of work prior to Christmas and now it lacks topology files and things have stopped working. It is also involved in a the introductory notebooks which require similar calls to that file (see below). Other models seem to be fine like Clennette2020.

![image](https://github.com/GPlates/gplately/assets/52948432/51437396-56ff-46b3-927c-4eb97438195c)

**Comment by ActiveMargins** [comment] 2024-01-29 16:40
Hi Michael
Resetting the directory seems to have worked. I set the directory to a different folder via
`model_download = pm_manager.get_model("Muller2019", data_dir="C:/Users/_____/AppData/Local/GPlates/GPlates")`
I was wondering how to find the original directory that it was downloading to either through a model manager method or default directory.

**Comment by michaelchin** [comment] 2024-01-29 23:06
> Hi Michael Resetting the directory seems to have worked. I set the directory to a different folder via `model_download = pm_manager.get_model("Muller2019", data_dir="C:/Users/_____/AppData/Local/GPlates/GPlates")` I was wondering how to find the original directory that it was downloading to either through a model manager method or default directory.

I think the default folder should be the "current working directory(./)" if the user did not give "data_dir" parameter. The "data_dir" can be found via "get_data_dir()" function. You need to call the function from a PlateModel object, such as model_download.get_data_dir().

**Comment by ActiveMargins** [comment] 2024-02-01 19:15
Perfect. Thank you this is resolved. My previous work is back to being operational and I now know where to look for the data directory. Thank you for your help!

**Comment by michaelchin** [comment] 2024-06-04 07:34
Customer seems happy. So, close this issue.

**Closed by michaelchin** 2024-06-04 07:34 UTC
