### ISSUE TITLE
Incorrect trench normal angle calculation

### ISSUE THREAD

**Issue by singhsatyampratap** [GPlates/gplately#269] opened 2024-09-11 05:46 UTC
Hi GPlately team,

I have encountered an issue with the trench normal angle calculation, specifically in the region of Eastern Australia. When attempting to draw a perpendicular profile, I noticed that the calculated angles appear to be incorrect in several instances.

![image](https://github.com/user-attachments/assets/a5494fa6-a4ae-4214-92a8-265a1b738831)

The issue seems to be consistent across multiple trials in Eastern Australia and across multiple plate models, though it may also occur elsewhere. Could you please look into this?

Regards,
Satyam

**Steps to reproduce the issue:**

```python
import gplately
from plate_model_manager import PlateModelManager
import numpy as np
from shapely.geometry import Point, LineString
import geopandas as gpd
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.mpl.gridliner as grd
import matplotlib.cm as cm

pm_manager = PlateModelManager()
muller2019_model = pm_manager.get_model("Muller2019", data_dir="plate-model-repo")
rotation_model = muller2019_model.get_rotation_model()
topology_features = muller2019_model.get_topologies()
static_polygons = muller2019_model.get_static_polygons()
coastlines = muller2019_model.get_coastlines()
continents = muller2019_model.get_continental_polygons()
COBs = muller2019_model.get_COBs()

## loading reconstruction
model = gplately.PlateReconstruction(rotation_model, topology_features, static_polygons)
time = 100 #Ma
subduction_data = model.tessellate_subduction_zones(time, return_geodataframe=True)



profiles=[]
trench_lats=[]
trench_lons=[]
n_steps=20
for i in range(0, len(subduction_data)-1):
    dlon1 = n_steps * np.sin(np.radians(subduction_data.iloc[i]['trench normal angle (degrees)']))
    dlat1 = n_steps * np.cos(np.radians(subduction_data.iloc[i]['trench normal angle (degrees)']))
    x1=subduction_data.iloc[i]['geometry'].x
    y1=subduction_data.iloc[i]['geometry'].y
    ilon1 = x1 + dlon1
    ilat1 = y1+ dlat1
    start_point = Point(x1+ 0.1*dlon1, y1+ 0.1*dlat1)
    end_point = Point(ilon1, ilat1)
    profile = LineString([start_point, end_point])
    profiles.append(profile)

central_longitude=180
Profile=gpd.GeoDataFrame(geometry=profiles)
mollweide_proj = f"+proj=moll +lon_0={central_longitude} +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs"

Profile=Profile.set_crs(mollweide_proj)




cmap='tab20c'
fig, axes = plt.subplots(2, 1, figsize=(16, 12), dpi=100, subplot_kw={'projection': ccrs.Mollweide(central_longitude=central_longitude)})

# First subplot (left side)
ax1 = axes[0]
ax1.gridlines(color='0.7', linestyle='--', xlocs=np.arange(-180, 180, 15), ylocs=np.arange(-90, 90, 15))

gplot1 = gplately.PlotTopologies(model, coastlines=coastlines, continents=continents, COBs=COBs, time=time)
# ax1.set_title('Subduction zones and mid-ocean ridges reconstructed to %i Ma' % (time))

# Plot shapefile features, subduction zones, and MOR boundaries at the specified time
gplot1.plot_continent_ocean_boundaries(ax1, color='b', alpha=0.05)
gplot1.plot_continents(ax1, facecolor='palegoldenrod', alpha=0.2)
gplot1.plot_coastlines(ax1, color='DarkKhaki')
gplot1.plot_ridges_and_transforms(ax1, color='red')
gplot1.plot_trenches(ax1, color='k',alpha=0.3)
gplot1.plot_subduction_teeth(ax1, color='k', alpha=0.7)

# Add subduction data plot (with a colorbar)
cbar1 = subduction_data.plot(ax=ax1, column='trench normal angle (degrees)', transform=ccrs.PlateCarree(), alpha=0.2, cmap=cmap, legend=False)

sm = cm.ScalarMappable(cmap=cmap)
sm.set_array(subduction_data['trench normal angle (degrees)'])
sm.set_clim(0, 360)

# Add colorbar using the same Axes object used for plotting
colorbar = plt.colorbar(sm, ax=ax1, orientation='vertical',shrink=0.6, label='trench normal angle (degrees)')

# Second subplot (right side)
ax2 = axes[1]
ax2.gridlines(color='0.7', linestyle='--', xlocs=np.arange(-180, 180, 15), ylocs=np.arange(-90, 90, 15))

gplot2 = gplately.PlotTopologies(model, coastlines=coastlines, continents=continents, COBs=COBs, time=time)
ax2.set_title('Profile View')

# Plot shapefile features
gplot2.plot_continent_ocean_boundaries(ax2, color='b', alpha=0.05)
gplot2.plot_continents(ax2, facecolor='palegoldenrod', alpha=0.2)
gplot2.plot_coastlines(ax2, color='DarkKhaki')
gplot2.plot_ridges_and_transforms(ax2, color='red')
gplot2.plot_trenches(ax2, color='k',alpha=0.2)
gplot2.plot_subduction_teeth(ax2, color='k')

# Add profile plot (with colorbar)
cbar2 = Profile.plot(ax=ax2, transform=ccrs.PlateCarree(), alpha=0.2)
# fig.colorbar(cbar2, ax=ax2, fraction=0.04, pad=0.04)

# Set the global extents for both subplots
ax1.set_global()
ax2.set_global()

# Adjust layout
plt.tight_layout()
plt.show()

**Comment by michaelchin** [comment] 2024-09-17 05:18
this might be related to https://github.com/GPlates/gplately/issues/188?????

Not sure until look into further

**Comment by michaelchin** [comment] 2024-10-16 04:33
I shall look into this a bit.

**Comment by jcannon-gplates** [comment] 2024-10-16 04:39
> I shall look into this a bit.

Thanks, if you find the issue is in the subduction convergence script let me know and I can take a deeper look there.

**Comment by michaelchin** [comment] 2024-10-16 04:41
> > I shall look into this a bit.
> 
> Thanks, if you find the issue is in the subduction convergence script let me know and I can take a deeper look there.

No problem. If it is related to this https://github.com/GPlates/gplately/issues/188, we can close two issues at once. Good deal.

**Comment by michaelchin** [comment] 2024-10-21 08:41
It seems somehow related to the lines are reversed in topology. I have no time to look into it further today. 

@jcannon-gplates any ideas?

<img width="997" alt="Screenshot 2024-10-21 at 7 19 45 PM" src="https://github.com/user-attachments/assets/a18a49f9-ea83-4129-aa2a-273b1119834d">
<img width="1045" alt="Screenshot 2024-10-21 at 7 36 18 PM" src="https://github.com/user-attachments/assets/5a604bce-bf9a-4c7d-8065-ecc7c379a70d">

**Comment by michaelchin** [comment] 2024-10-21 08:43
The lines here seem reversed to me.

<img width="927" alt="Screenshot 2024-10-21 at 7 42 23 PM" src="https://github.com/user-attachments/assets/fb2e5872-4e3e-4be7-87c7-4965b3e6b974">

**Comment by jcannon-gplates** [comment] 2024-10-21 10:33
> It seems somehow related to the lines are reversed in topology.

Thanks, yes that was the problem. I've fixed it in #296 (it's failing the regular unit tests though).

And thanks for @singhsatyampratap for the nice, reproducible sample code.

![image](https://github.com/user-attachments/assets/d7da54f9-d8e8-40d3-bb72-2e3e30368a81)

By the way, running the sample code gave [this](https://github.com/shapely/shapely/issues/2098) error (on Windows) that was fixed by updating shapely to 2.0.6 (from 2.0.4). Not sure if it's worth restricting shapely to >= 2.0.6 though (might be too limiting for some installations).

**Comment by jcannon-gplates** [comment] 2024-10-21 10:45
I think the regular tests are failing [here](https://github.com/GPlates/gplately/blob/d347b158bbf2dd16c835da28b9ce0db48d94ee58/tests-dir/pytestcases/test_1_reconstructions.py#L148). Probably because the trench normal (azimuth) has now changed in that small region (that was just fixed), and so the trench-projected points into the age grid test raster are getting different values. Might need to change `trench_arc_distance` to something other than 281 - @michaelchin can I leave that with you?

**Comment by michaelchin** [comment] 2024-10-21 22:59
> I think the regular tests are failing [here](https://github.com/GPlates/gplately/blob/d347b158bbf2dd16c835da28b9ce0db48d94ee58/tests-dir/pytestcases/test_1_reconstructions.py#L148). Probably because the trench normal (azimuth) has now changed in that small region (that was just fixed), and so the trench-projected points into the age grid test raster are getting different values. Might need to change `trench_arc_distance` to something other than 281 - @michaelchin can I leave that with you?

Sure, I will have a look.

**Comment by michaelchin** [comment] 2024-10-23 08:37
@GPlates/gplately-dev 

With my very much limited knowledge about trenches, I can only increase the error margin from 1000 to 3000 in test_cont_arc_length() to make the tests pass. I am not sure if it makes sense. I think, now with the correct trench normal, a bit extra trenches are counted in now. I think it is the reason why the arc length increased.

Any ideas?

**Comment by jcannon-gplates** [comment] 2024-10-24 07:13
I think you're right about the trench length increasing. That would be due to the correct trench normal direction (along the East coast of Australia) now sampling inside the continent grid (inverse of age grid) giving a larger total trench length along continents (than before).

One option, instead of increasing the error margin, is to adjust the approximate lengths [here](https://github.com/GPlates/gplately/blob/d347b158bbf2dd16c835da28b9ce0db48d94ee58/tests-dir/pytestcases/test_1_reconstructions.py#L156) ?

**Comment by michaelchin** [comment] 2024-10-24 07:21
> One option, instead of increasing the error margin, is to adjust the approximate lengths [here](https://github.com/GPlates/gplately/blob/d347b158bbf2dd16c835da28b9ce0db48d94ee58/tests-dir/pytestcases/test_1_reconstructions.py#L156) ?

Good idea! But I am not sure where the number came from...

**Comment by jcannon-gplates** [comment] 2024-10-24 07:42
> Good idea! But I am not sure where the number came from...

It might have originally come from `model.total_continental_arc_length()` itself, and maybe rounded to nearest 100kms.

In any case, I measured the distance along the problematic part of the line (by digitizing a rough white line - see image below) and it came to around 2500km. The red line is the white line moved along trench normal to sample inverse age grid. Not all of continent (inverse age grid) will get sampled, but most of it. So you can probably just increase 44000 by around 2000km (and reset the error margin back to 1000) and see if it passes.

![image](https://github.com/user-attachments/assets/d094c594-b3eb-484a-ad0c-cccfb1e8846f)

**Comment by michaelchin** [comment] 2024-10-25 00:45
I have changed error margin back to 1000 and changed the approx_lengths at 100ma from 44000 to 46000 in test_cont_arc_length() function. The tests have passed. Shall I consider this issue done?

**Comment by jcannon-gplates** [comment] 2024-10-25 03:33
> The tests have passed. Shall I consider this issue done?

Yes I think it's all good now 👍. That bug has been in the subduction convergence script for ages - good to have it finally discovered and sorted!

**Closed** 2024-10-25 04:27 UTC
Labels: bug, medium
